version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: insight-{{ checksum "pom.xml" }}
#      - run: ./mvnw dependency:go-offline
      - run: ./mvnw package -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: insight-{{ checksum "pom.xml" }}
      - run: ./mvnw package
      - store_test_results:
          path: target/surefire-reports
      - run: bash <(curl -s https://codecov.io/bash)
