
insight:
  logging:
    truncateMessage: true
    truncateMessageLength: 200
  tracing:
    before: '[ entering < %s > with args %s ]'
    afterThrowing: '[ exception thrown by < %s > with args %s with message %s ]'
    afterReturning: '[ leaving < %s > returning %s ]'
  profiling:
    around: '[ time taken to execute < %s > = %sms ]'
